#!/bin/bash
#
# dist
# ----
# Copyright : (c) 2012, Jeremie Dimino <jeremie@dimino.org>
# Licence   : BSD3
#
# Script to build the release

set -e

# Extract project parameters from _oasis
NAME=`oasis query Name 2> /dev/null`
VERSION=`oasis query Version 2> /dev/null`

if git show-ref refs/tags/$VERSION &> /dev/null; then
    echo "Tag $VERSION already exists!" >&2
    exit 1
fi

if [[ "$(git status --porcelain)" != "" ]]; then
    echo "Repository is not clean" >&2
    exit 1
fi

# Create a branch for the release
BRANCH=release-$VERSION
git checkout -b release-$VERSION

# Generate files
oasis setup

# Set release mode in the Makefile
sed 's/^SETUP := setup-dev.exe.*/SETUP := setup.exe/' Makefile > Makefile.new
mv Makefile.new Makefile

# Remove this script
rm -f dist

# Commit
git add --all
git commit -m "run 'oasis setup'"
git tag $VERSION

git checkout master
git branch -D $BRANCH
